# Generated by Django 4.1.2 on 2025-08-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egroceryapp', '0017_productview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_to_cart',
            old_name='prodcut_Id_Add',
            new_name='product_Id_Add',
        ),
    ]
